
[2021-11-23 15:00:58,417: INFO: 01_base_model_creation]: 
********************
[2021-11-23 15:00:58,417: INFO: 01_base_model_creation]: >>>>> stage Creating base model started <<<<<
[2021-11-23 15:00:58,417: ERROR: 01_base_model_creation]: 'Namespace' object has no attribute 'params'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 69, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
AttributeError: 'Namespace' object has no attribute 'params'
[2021-11-23 15:03:20,755: INFO: 01_base_model_creation]: 
********************
[2021-11-23 15:03:20,755: INFO: 01_base_model_creation]: >>>>> stage Creating base model started <<<<<
[2021-11-23 15:03:20,755: ERROR: 01_base_model_creation]: 'Namespace' object has no attribute 'params'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 84, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
AttributeError: 'Namespace' object has no attribute 'params'
[2021-11-23 15:04:27,113: INFO: 01_base_model_creation]: 
********************
[2021-11-23 15:04:27,114: INFO: 01_base_model_creation]: >>>>> stage Creating base model started <<<<<
[2021-11-23 15:04:27,114: ERROR: 01_base_model_creation]: [Errno 2] No such file or directory: 'configs/config.yaml'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 84, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 24, in main
    config = read_yaml(config_path)
  File "c:\users\saipr\downloads\desktop\data science\ineuron\transfer_learning_demo\src\utils\common.py", line 8, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/config.yaml'
[2021-11-23 15:06:13,333: INFO: 01_base_model_creation]: 
********************
[2021-11-23 15:06:13,333: INFO: 01_base_model_creation]: >>>>> stage Creating base model started <<<<<
[2021-11-23 15:06:13,335: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-23 15:06:32,681: ERROR: 01_base_model_creation]: module 'keras.api._v2.keras' has no attribute 'model'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 84, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 49, in main
    model = tf.keras.model.Sequential(LAYERS)
AttributeError: module 'keras.api._v2.keras' has no attribute 'model'
[2021-11-23 15:08:17,423: INFO: 01_base_model_creation]: 
********************
[2021-11-23 15:08:17,423: INFO: 01_base_model_creation]: >>>>> stage Creating base model started <<<<<
[2021-11-23 15:08:17,423: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-23 15:09:24,462: INFO: common]: created directory at: artifacts\models
[2021-11-23 15:09:25,460: INFO: 01_base_model_creation]: >>>>> stage Creating base model completed!<<<<<

[2021-11-23 15:11:31,344: INFO: 01_base_model_creation]: 
********************
[2021-11-23 15:11:31,344: INFO: 01_base_model_creation]: >>>>> stage Creating base model started <<<<<
[2021-11-23 15:11:31,344: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-23 15:12:24,083: INFO: common]: created directory at: artifacts\models
[2021-11-23 15:12:24,256: INFO: 01_base_model_creation]: base model is saved at artifacts\models\base_model.h5
[2021-11-23 15:12:25,211: INFO: 01_base_model_creation]: evaluation metrics [0.3162649869918823, 0.9092000126838684]
[2021-11-23 15:12:25,275: INFO: 01_base_model_creation]: >>>>> stage Creating base model completed!<<<<<

